name: gear_ui
description: "Project semester 4 at Aptech"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  flutter_launcher_icons: ^0.13.1
  get: ^4.6.6
  go_router: ^13.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  path: ^1.8.3
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.1
  strings: 2.0.3
  font_awesome_flutter: ^10.7.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  rxdart: ^0.27.7
  email_validator: ^2.1.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/fallback/
  #  - assets/images/logo/
    - assets/images/sidebar/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

